config/routes.rb
Gifgovern::Application.routes.draw do
    resources :comments
    resources :tags
    resources :ip_actions
    
    
    devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
    
    root :to => "gifs#index"
    match '/gifs/navigate_left/:gif_offset' => 'gifs#navigate_left'
    match '/gifs/navigate_right/:gif_offset' =>'gifs#navigate_right'
    
    match '/gifs/iframe/:id' => 'gifs#iframe'
    match '/gifs/reverse/:id' => 'gifs#reverse'
    match '/gifs/latest' => 'gifs#latest'
    match '/gifs/random' => 'gifs#random'
    
    resources :gifs
    match 't/:tag' => 'gifs_of_tag#index'
    match 't/:tag/:id' => 'gifs_of_tag#show'
    resources :gifs_of_tag, :path => 't'
    
    resources :votes
    
    match 'special/whoarewe', :controller => 'special', :action => 'howarewe'
    match 'special/policy', :controller => 'special', :action => 'termsOfServices'
    match 'special/howto', :controller => 'special', :action => 'howto'
    match 'special/alert', :controller => 'special', :action => 'alert'
    match 'userspace', :controller => 'special', :action => 'userspace'
    match 'userspace/:username' => 'special#userspace'
    match 'special/redirection', :controller => 'special', :action => 'redirection'
    
    match 'player' => 'special#player'
    
    
    
    
    
    
    
    
    
    
    
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    attr_accessible :commentaire,:gif,:gif_name
    belongs_to :user
    belongs_to :gif
    belongs_to :comment
    
    validates_length_of :commentaire, :minimum => 2, :maximum => 150, :allow_blank => false
    
    #use virtual attribute 
    def gif_name=(name)
        #use find_by_name due to a strange issue caused by FriendlyID
        self.gif=Gif.find_by_name(name)
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController  
    #invoke Cancan, CommentsController's actions' permissions is defined with ability.rb, technical details see : https://github.com/ryanb/cancan
    load_and_authorize_resource

    # GET /comments/1
    # GET /comments/1.json
    def show
        @comment = Comment.find(params[:id])

        respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @comment }
        end
    end

    # GET /comments/new
    # GET /comments/new.json
    def new
        @comment = Comment.new

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @comment }
        end
    end

    # GET /comments/1/edit
    def edit
        @comment = Comment.find(params[:id])
    end

    # POST /comments
    # POST /comments.json
    def create    
        @comment = Comment.new(params[:comment])
        @comment.user=current_user
        respond_to do |format|
            if @comment.save
                #format.html { redirect_to :controller => 'gifs', :action => 'show', :id => @comment.gif.name,  notice: 'Comment created.' }
                #format.json { render json: @comment, status: :created, location: @comment }      
                format.html { render :partial => "comments/comment_render", :locals => { :comment => @comment }, :layout => false, :status => :created }
            end
        end
    end


    def index
        @comment = Comment.all

        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @comment }
        end
    end

    # PUT /comments/1
    # PUT /comments/1.json
    def update
        @comment = Comment.find(params[:id])

        respond_to do |format|
            if @comment.update_attributes(params[:comment])
                format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @comment.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /comments/1
    # DELETE /comments/1.json
    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy

        respond_to do |format|
            format.html { redirect_to :controller => 'comments', :action => 'index', notice: 'Comment deleted.' }
            format.json { head :no_content }
        end
    end
end

app/views/comments/_comment_render.html.erb
<div class="panel panel-default">
    <div class="panel-heading"> 
        <%= link_to  comment.user.username, {:action => 'userspace', :controller => "special", :username => comment.user.username  }, :class => 'link_to_user' %>
        : <%= time_ago_in_words(comment.created_at)+" ago" %>
    </div>
    <div class="panel-body">
        <%= comment.commentaire %>
    </div>
</div>

app/views/comments/_comment_section.html.erb
<!-- this file defines the comment section of a gif page -->
<div class="row" id="comment_section">
    <div class="col-md-3" id="gif_context">
        <div class="panel panel-default gif_definition_panel">
        <!-- like unlike bar, to be implemented
            <div>
                <div class="progress" style="height: 5px; margin-bottom: 5px; background-color: red">
                    <div class="progress-bar progress-bar-success" role="progressbar" style="width: 60%;">
                    </div>
                    <div class="progress-bar progress-bar-danger" role="progressbar" style="width: 40%;">
                    </div>
                </div>
            </div>
            -->
            <div>
                <%= time_ago_in_words(gif.created_at)+" ago"  %> - <span class="badge"><%= @gif.views %></span> views
            </div>
            <div>
                by <%= link_to  @gif.user.username, {:action => 'userspace', :controller => "special", :username => @gif.user.username  }, :class => 'link_to_user' %>          


                from <%= link_to "Source", @gif.get_image_source %>
            </div>
            <div>
                tags : 
                <% @gif.tags.take(10).each do |t| %>
                <%= link_to(t.name, :action => 'index', :controller => 'gifs_of_tag', :tag => t.name.delete('#') ) %>   
                <% end %>
            </div>
            <div>
                <% if can? :update, @gif %>
                        <p>
                            <%= button_to('Edit', edit_gif_path, :class => "", :method => :get) %>                
                        </p>                             
                        <% end %>
            </div>
            <!--
            <div>
                 render :partial => 'partial_renders/facebookstuff' %>
            </div>
            -->
        </div>
    </div>
    <div class="col-md-9">
        <div class="comments row">
            <div class="comment row">
                <div class="col-md-11">
                    <%= form_for Comment.new, :html => { :multipart => true, :id => "ajax_comment",:remote => true, :"role" => "form" , :class => "comment_form" } do |f| %>

                    <div class="form-group">
                        <%= f.text_area :commentaire, :placeholder => "Your comment/Ton avis...",:rows => "1", :id => "new_message", :class => "form-control comment_txt_area" %>
                        <%= f.hidden_field :gif_name, :value => @gif.name %>
                    </div>
                </div>
                <div class="col-md-1">
                    <button type="submit" class="btn" id="ajax_comment_btn" style="background-color:#2b2b2b;"><p class="text-primary">Submit</p></button>
                    <% end %>
                </div>
            </div>  
            <div id="comments_panel">
                <% @gif.comment.reverse.each do |comment| %>
                <%= render :partial => 'comments/comment_render', :locals => {:comment => comment} %>
                <% end %>
            </div>    
        </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(function(){
        $("#ajax_comment").submit(function(){
            var dataSet = $(this).serialize();
            $.ajax({
                type: "POST",
                url: $(this).attr("action"),
                data: dataSet,
                beforeSend: function(data, textStatus, jqXHR){
                    //to define before action
                },
                success: function(data, textStatus, jqXHR){
                    $("#comments_panel").prepend(jqXHR.responseText);
                },
                error: function(data, textStatus, jqXHR){
                    alert("PLease login to comment....");
                },
            });
            return false;
        });
    })
    $(function(){
        $("#ajax_vote").submit(function(){
            var dataSet = $(this).serialize();
            $.ajax({
                type: "POST",
                url: $(this).attr("action"),
                data: dataSet,
                beforeSend: function(data, textStatus, jqXHR){
                    //to define before action
                },
                success: function(data, textStatus, jqXHR){
                    $("#upvotes_span").text(jqXHR.responseText);
                },
                error: function(data, textStatus, jqXHR){
                    alert("something went wrong with comment system....");
                },
            });
            return false;
        });
    })
</script>

app/views/comments/index.html.erb
<h1 class="title">Listing comments</h1>

<table border="1px">
    <tr>
        <th></th>
        <th></th>
        
    </tr>
    <% if can? :read, Comment %>	
    <% @comment.each do |comment| %>
    <tr border="1px">
        <td border="1px">  	
            <%= link_to(comment.commentaire, :action => 'show', :controller => 'gifs', :id =>(comment.gif.nil? ? '1' :comment.gif.name)) %>   
             <% if can? :destroy, Comment %>	
            <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
            <% else %>
                <td></td> 
            <% end %>
    </tr>
    <% end %>
    <% end %>
</table>

<br />