config/routes.rb
Gifgovern::Application.routes.draw do
    resources :comments
    resources :tags
    resources :ip_actions
    
    
    devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }
    
    root :to => "gifs#index"
    match '/gifs/navigate_left/:gif_offset' => 'gifs#navigate_left'
    match '/gifs/navigate_right/:gif_offset' =>'gifs#navigate_right'
    
    match '/gifs/iframe/:id' => 'gifs#iframe'
    match '/gifs/reverse/:id' => 'gifs#reverse'
    match '/gifs/latest' => 'gifs#latest'
    match '/gifs/random' => 'gifs#random'
    
    resources :gifs
    match 't/:tag' => 'gifs_of_tag#index'
    match 't/:tag/:id' => 'gifs_of_tag#show'
    resources :gifs_of_tag, :path => 't'
    
    resources :votes
    
    match 'special/whoarewe', :controller => 'special', :action => 'howarewe'
    match 'special/policy', :controller => 'special', :action => 'termsOfServices'
    match 'special/howto', :controller => 'special', :action => 'howto'
    match 'special/alert', :controller => 'special', :action => 'alert'
    match 'userspace', :controller => 'special', :action => 'userspace'
    match 'userspace/:username' => 'special#userspace'
    match 'special/redirection', :controller => 'special', :action => 'redirection'
    
    match 'player' => 'special#player'
    
    
    
    
    
    
    
    
    
    
    
end

app/models/tag.rb
class Tag  < ActiveRecord::Base
    #FriendId gem, make tag name as ID in the tags table, see the details on https://github.com/norman/friendly_id/
    extend FriendlyId
    friendly_id :name

    attr_accessible :description,:name,:howmany,:user, :tag_type
    belongs_to :user
    has_and_belongs_to_many :gifs

    def to_param
        "#{self.name}"
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    #invoke Cancan, TagsController actions' permissions is defined with ability.rb, technical details see : https://github.com/ryanb/cancan
    load_and_authorize_resource
    # GET /tags
    # GET /tags.json
    def index
        @tags = Tag.all
        @grouped = {}
        @gifs = Gif.accessible_by(current_ability).order('views DESC').limit(27)	
        @tags.each do |company|
            letter = company.name.slice(1,1).upcase
            @grouped[letter] ||= []
            @grouped[letter] << company
        end

        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @tags }
        end
    end

    # GET /tags/1/edit
    def edit
        @tag = Tag.find(params[:id])
    end

    # POST /tags
    # POST /tags.json
    def create
        @tag = Tag.new(params[:tag])

        respond_to do |format|
            if @tag.save
                format.html { redirect_to '/tags', notice: 'Tag was successfully created.' }
                format.json { render json: @tag, status: :created, location: @tag }
            else
                format.html { render action: "new" }
                format.json { render json: @tag.errors, status: :unprocessable_entity }
            end
        end
    end

    # PUT /tags/1
    # PUT /tags/1.json
    def update
        @tag = Tag.find(params[:id])

        respond_to do |format|
            if @tag.update_attributes(params[:tag])
                format.html { redirect_to '/tags', notice: 'Tag was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @tag.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /tags/1
    # DELETE /tags/1.json
    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy

        respond_to do |format|
            format.html { redirect_to tags_url }
            format.json { head :no_content }
        end
    end
end

app/views/tags/_form.html.erb
<%= form_for @tag, :html => { :class => "form-horizontal", :role => "form" } do |f| %>

<div class="form-group">
    <label class="col-sm-2 control-label">Tag name</label>
    <div class="col-sm-4">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Description</label>
    <div class="col-sm-4">
      <%= f.text_field :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
       <%= f.check_box( "tag_type", {}, "nsfw", "sfw") %> 
        <label>
          NSFW?
        </label>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">submit</button>
    </div>
  </div>

<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1 class="title">Listing tags</h1>

<table width="100%">
    <tr>
        <th> by alphebet</th>
        <th> by population</th>
        <th> Top gifs </th>
    </tr>

    <tr >

        <td  style="vertical-align:top;">
            <ul>
                <% @grouped.keys.sort.each do |letter| %>
                <li>
                    <h2><%= letter %></h2>
                    <ul>
                        <% @grouped[letter].each do |tag| %>
                        <li>
                            <%= link_to(tag.name , :action => 'index', :controller => 'gifs_of_tag', :tag => tag.name.delete("#")) %>   	
                        </li>
                        <% end %>
                    </ul>
                </li>
                <% end %>
            </ul>
        </td>


        <td style="vertical-align:top;">
            <ul>
                <% @tags.sort_by{|u| u.howmany  }.reverse.each do |tag| %>
                <li>
                    <%= link_to(tag.name + ' ('+tag.howmany.to_s+')', :action => 'index', :controller => 'gifs_of_tag', :tag => tag.name.delete("#")) %>   	
                        <% if can? :update, Tag %>
                        <%= link_to 'Edit', edit_tag_path(tag) %>
                        <% end %>
                        <% if can? :destroy, Tag %>
                        <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %>
                        <% end %>
                </li>
                <% end %>
            </ul>
        </td>


        <td style="vertical-align:top;">
            <ul>
                <% @gifs.sort_by{|u| u.views  }.reverse.each do |gif| %>

                <li>
                    <%= link_to image_tag((gif.upload.url(:thumb)) , :border=>0, :class => "style_image"), 
    { :action => 'show', :controller => 'gifs', :id => gif.name,:tag => params[:tag]  }, :class => 'img-thumbnail', :'data-src' => 'holder.js/300x200' %>

                </li>
                <% end %>
            </ul>
        </td>
    </tr>
</table>